### ISSUE TITLE
Errors if the object is in the Blazer template before set

### ISSUE THREAD

**Issue by ibc** [eface2face/reactive-object#1]
Let's have a Blaze template containing something such as:

``` html
<video class="remote {{#unless remoteVideoShown}}hidden{{/unless}}" autoplay></video>
```

and:

``` js
var ReactiveObject = require('reactive-object')(jquery.Meteor);
[...]
this._status = new ReactiveObject();
[...]
.reactive('status', this._status)
[...]
.helpers('remoteVideoShown',    function()
{
    if (self._status.get('focus'))
        return false;
    else
        return true;
})
```

and let `status` be an object such as `{focus: true}`, but its reactive variable is set later with a setter in the template (`setStatus(status)`).

In this case Blaze produces an error since `this._status` is not yet set when the template is initiated:

```
Exception in template helper: TypeError: Cannot read property 'focus' of undefined
```

Is there any way to avoid this error (other than using `#with status` in the template)?

**Comment by murillo128** [comment]
That's intended usage, either you don't initialize so it is null and you have to use {{#with}} or you intitialize it on the constructor
this._status = new ReactiveObject({focus:false});
